//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSearch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchInTitle {
            get {
                return ((bool)(this["SearchInTitle"]));
            }
            set {
                this["SearchInTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchInUserName {
            get {
                return ((bool)(this["SearchInUserName"]));
            }
            set {
                this["SearchInUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchInUrl {
            get {
                return ((bool)(this["SearchInUrl"]));
            }
            set {
                this["SearchInUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchInNotes {
            get {
                return ((bool)(this["SearchInNotes"]));
            }
            set {
                this["SearchInNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchInOther {
            get {
                return ((bool)(this["SearchInOther"]));
            }
            set {
                this["SearchInOther"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchInGroupPath {
            get {
                return ((bool)(this["SearchInGroupPath"]));
            }
            set {
                this["SearchInGroupPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchInGroupName {
            get {
                return ((bool)(this["SearchInGroupName"]));
            }
            set {
                this["SearchInGroupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchInTags {
            get {
                return ((bool)(this["SearchInTags"]));
            }
            set {
                this["SearchInTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCaseSensitive {
            get {
                return ((bool)(this["SearchCaseSensitive"]));
            }
            set {
                this["SearchCaseSensitive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchIgnoreGroupSettings {
            get {
                return ((bool)(this["SearchIgnoreGroupSettings"]));
            }
            set {
                this["SearchIgnoreGroupSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230, 247, 233")]
        public global::System.Drawing.Color BackColorSuccess {
            get {
                return ((global::System.Drawing.Color)(this["BackColorSuccess"]));
            }
            set {
                this["BackColorSuccess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 247, 204")]
        public global::System.Drawing.Color BackColorSearching {
            get {
                return ((global::System.Drawing.Color)(this["BackColorSearching"]));
            }
            set {
                this["BackColorSearching"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 192, 192")]
        public global::System.Drawing.Color BackColorOnError {
            get {
                return ((global::System.Drawing.Color)(this["BackColorOnError"]));
            }
            set {
                this["BackColorOnError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("245, 245, 245")]
        public global::System.Drawing.Color BackColorNormalUnFocused {
            get {
                return ((global::System.Drawing.Color)(this["BackColorNormalUnFocused"]));
            }
            set {
                this["BackColorNormalUnFocused"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("229, 243, 255")]
        public global::System.Drawing.Color BackColorNormalFocused {
            get {
                return ((global::System.Drawing.Color)(this["BackColorNormalFocused"]));
            }
            set {
                this["BackColorNormalFocused"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ControlWidth {
            get {
                return ((int)(this["ControlWidth"]));
            }
            set {
                this["ControlWidth"] = value;
            }
        }
    }
}
